apiVersion: v1
kind: Service
metadata:
  name: sftp-background-service
  namespace: dev
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: sftp-background-service
  type: LoadBalancer
  loadBalancerIP: 10.10.2.0
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP